//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expressium.LivingDoc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expressium.LivingDoc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;title&gt;Expressium LivingDoc&lt;/title&gt;
        ///		&lt;link href=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;
        ///		&lt;link href=&quot;https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css&quot; rel=&quot;stylesheet&quot;&gt;.
        /// </summary>
        internal static string Heads {
            get {
                return ResourceManager.GetString("Heads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;script&gt;
        ///        function loadScenario(x) {
        ///            var featureId = x.getAttribute(&apos;data-featureid&apos;);
        ///            var scenarioId = x.getAttribute(&apos;data-scenarioid&apos;);
        ///            var feature = document.getElementById(featureId).innerHTML;
        ///            var scenario = document.getElementById(scenarioId).innerHTML;
        ///
        ///            document.getElementById(&apos;splitter-right&apos;).innerHTML = feature + scenario;
        ///
        ///            clearActiveListItems();
        ///            x.classList.add(&apos;active&apos;);
        ///        }
        ///    &lt;/s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;script&gt;
        ///        const splitter = document.getElementById(&apos;splitter&apos;);
        ///        const splitterLeft = document.getElementById(&apos;splitter-left&apos;);
        ///        const splitterRight = document.getElementById(&apos;splitter-right&apos;);
        ///
        ///        let isDragging = false;
        ///
        ///        splitter.addEventListener(&apos;mousedown&apos;, (e) =&gt; {
        ///            isDragging = true;
        ///            document.body.style.cursor = &apos;col-resize&apos;;
        ///        });
        ///
        ///        document.addEventListener(&apos;mousemove&apos;, (e) =&gt; {
        ///            if (!isDragging) return [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Splitter {
            get {
                return ResourceManager.GetString("Splitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///    :root {
        ///        
        ///        /* Bootstrap Grayscale */
        ///        --bs-gray-075: #fafbfc;
        ///        --bs-gray-100: #f8f9fa;
        ///        --bs-gray-125: #f2f4f6;
        ///        --bs-gray-150: #f1f3f5;
        ///        --bs-gray-200: #e9ecef;
        ///        --bs-gray-300: #dee2e6;
        ///        --bs-gray-400: #ced4da;
        ///        --bs-gray-450: #bec5cc;
        ///        --bs-gray-500: #adb5bd;
        ///        --bs-gray-600: #6c757d;
        ///        --bs-gray-650: #5b636a;
        ///        --bs-gray-700: #495057;
        ///        --bs-gray-800: #343a40;
        ///        --bs-gra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
    }
}
