using Expressium.LivingDoc.Generators;
using Expressium.LivingDoc.Models;
using System.Linq;

namespace Expressium.LivingDoc.UnitTests.Generators
{
    public class LivingDocContentGeneratorTests
    {
        [Test]
        public void LivingDocContentGenerator_GenerateHeader()
        {
            var project = new LivingDocProject
            {
                Title = "Test Project",
                Date = new System.DateTime(2024, 6, 1, 13, 5, 37)
            };

            var generator = new LivingDocContentGenerator(project);

            var listOfLines = generator.GenerateHeader();

            Assert.That(listOfLines, Is.Not.Null);
            Assert.That(listOfLines.Count, Is.EqualTo(5));
            Assert.That(listOfLines[0], Is.EqualTo("<!-- Header Section -->"));
            Assert.That(listOfLines[1], Is.EqualTo("<header>"));
            Assert.That(listOfLines[2], Is.EqualTo("<span class='project-name'>Test Project</span><br />"));
            Assert.That(listOfLines[3], Is.EqualTo("<span class='project-date'>Generated Sat 1 Jun 2024 at 13:05:37 GMT+2</span>"));
            Assert.That(listOfLines[4], Is.EqualTo("</header>"));
        }

        [Test]
        public void LivingDocContentGenerator_GenerateNavigation()
        {
            var project = new LivingDocProject();

            var generator = new LivingDocContentGenerator(project);

            var listOfLines = generator.GenerateNavigation();

            Assert.That(listOfLines, Is.Not.Null);
            Assert.That(listOfLines.Count, Is.EqualTo(8));
            Assert.That(listOfLines[0], Is.EqualTo("<!-- Project Navigation Section -->"));
            Assert.That(listOfLines[2], Does.Contain("title='Overview'"));
            Assert.That(listOfLines[3], Does.Contain("title='Features List View'"));
            Assert.That(listOfLines[4], Does.Contain("title='Scenarios List View'"));
            Assert.That(listOfLines[5], Does.Contain("title='Steps List View'"));
            Assert.That(listOfLines[6], Does.Contain("title='Analytics'"));
        }

        [Test]
        public void LivingDocContentGenerator_GenerateSplitter()
        {
            var project = new LivingDocProject();

            var generator = new LivingDocContentGenerator(project);
            var listOfLines = generator.GenerateSplitter();

            Assert.That(listOfLines, Is.Not.Null);
            Assert.That(listOfLines, Does.Contain("<!-- Splitter Wrapper Section -->"));
            Assert.That(listOfLines, Does.Contain("<!-- Left Splitter Section -->"));
            Assert.That(listOfLines, Does.Contain("<!-- Splitter Section -->"));
            Assert.That(listOfLines, Does.Contain("<!-- Right Splitter Section -->"));
            Assert.That(listOfLines, Does.Contain("<!-- Content Splitter Script -->"));
        }

        [Test]
        public void LivingDocContentGenerator_GenerateViewPreFilters()
        {
            var project = new LivingDocProject();

            var generator = new LivingDocContentGenerator(project);
            var listOfLines = generator.GenerateViewPreFilters();

            Assert.That(listOfLines, Is.Not.Null);
            Assert.That(listOfLines, Does.Contain("<!-- View Title Section -->"));
            Assert.That(listOfLines, Does.Contain("<!-- PreFilters Section -->"));
            Assert.That(listOfLines, Does.Contain("<span id='view-title' class='page-name'>Overview</span>"));
            Assert.That(listOfLines.Count(l => l.Contains("data-prefilter")), Is.EqualTo(4));
        }

        [Test]
        public void LivingDocContentGenerator_GenerateFilter()
        {
            var project = new LivingDocProject();

            var generator = new LivingDocContentGenerator(project);
            var listOfLines = generator.GenerateFilter();

            Assert.That(listOfLines, Is.Not.Null);
            Assert.That(listOfLines, Does.Contain("<!-- Filter Section -->"));
            Assert.That(listOfLines, Does.Contain("<input onkeyup='filterView()' class='filter-keywords' id='filter-by-keywords' type='text' placeholder='Filter by Keywords'>"));
        }

        [Test]
        public void LivingDocContentGenerator_GenerateFooter()
        {
            var project = new LivingDocProject();

            var generator = new LivingDocContentGenerator(project);

            var listOfLines = generator.GenerateFooter();

            Assert.That(listOfLines, Is.Not.Null);
            Assert.That(listOfLines.Count, Is.EqualTo(4));
            Assert.That(listOfLines[0], Is.EqualTo("<!-- Footer Section -->"));
            Assert.That(listOfLines[1], Is.EqualTo("<footer>"));
            Assert.That(listOfLines[2], Does.Contain($"Generated by Expressium LivingDoc"));
            Assert.That(listOfLines[3], Is.EqualTo("</footer>"));
        }
    }
}
