//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expressium.TestExecutionReport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Expressium.TestExecutionReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 		&lt;meta charset=&quot;UTF-8&quot;&gt;
        ///		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///		&lt;title&gt;Expressium LivingDoc&lt;/title&gt;
        ///		&lt;link href=&quot;https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot;&gt;.
        /// </summary>
        internal static string Heads {
            get {
                return ResourceManager.GetString("Heads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;script&gt;
        ///        function loadScenario(x) {
        ///            let details = document.getElementById(x).innerHTML;
        ///            document.getElementById(&apos;right-section&apos;).innerHTML = details;
        ///        }
        ///    &lt;/script&gt;
        ///	&lt;script&gt;
        ///		function presetScenarios(x) {
        ///			let input = document.getElementById(&quot;scenario-filter&quot;);
        ///            input.value = x;
        ///
        ///            filterScenarios();
        ///		}
        ///	&lt;/script&gt;
        ///    &lt;script&gt;
        ///        function filterScenarios() {
        ///            var input = document.getElementById(&quot;scenario-f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Scripts {
            get {
                return ResourceManager.GetString("Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &lt;script&gt;
        ///        const splitter = document.getElementById(&apos;splitter&apos;);
        ///        const leftSection = document.getElementById(&apos;left-section&apos;);
        ///        const rightSection = document.getElementById(&apos;right-section&apos;);
        ///
        ///        let isDragging = false;
        ///
        ///        splitter.addEventListener(&apos;mousedown&apos;, (e) =&gt; {
        ///            isDragging = true;
        ///            document.body.style.cursor = &apos;col-resize&apos;;
        ///        });
        ///
        ///        document.addEventListener(&apos;mousemove&apos;, (e) =&gt; {
        ///            if (!isDragging) return;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SplitterScript {
            get {
                return ResourceManager.GetString("SplitterScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		&lt;style&gt;
        ///        body, html {
        ///            height: 100%;
        ///            margin: 0;
        ///            overflow: hidden;
        ///        }
        ///
        ///        #content-wrapper {
        ///            display: flex;
        ///            height: calc(100% - 98px); /* Adjust for header and footer height */
        ///            flex-direction: row; /* Change to row for vertical splitter */
        ///        }
        ///
        ///        #splitter {
        ///            width: 2px;
        ///            background: #ddd;
        ///            cursor: col-resize;
        ///        }
        ///
        ///        #left-section, #right-sect [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
    }
}
